- name: Install WordPress
  hosts: node
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - nginx
    - php
    - wp
#- name: Install MySQL
#  hosts: db
#  remote_user: ubuntu
#  become: yes
#  become_method: sudo
#  roles:
#    - mysql

